apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2022-04-12T21:01:20Z"
  generation: 1
  labels:
    app: customers
  name: customers
  namespace: cnj
  resourceVersion: "44905"
  uid: 4d33bdde-ff5c-4531-a56d-9c973db52488
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: customers
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: customers
    spec:
      containers:
      - image: abidinkiremitci/cnj-basics:latest
        imagePullPolicy: Always
        name: cnj-basics
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/liveness
        readinessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/readiness
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
