apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2022-04-10T15:12:00Z"
  generation: 1
  labels:
    app: customers
  name: customers
  namespace: cnj
  resourceVersion: "17666"
  uid: 14afb65b-4948-4d29-9792-141c7dad1935
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: customers
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: customers
    spec:
      containers:
      - image: abidinkiremitci/cnj-basics:latest
        imagePullPolicy: Always
        name: cnj-basics
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
