apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2022-04-12T21:01:20Z"
  labels:
    kubernetes.io/metadata.name: cnj
  name: cnj
  resourceVersion: "44899"
  uid: acc57248-e4f8-4bf8-bd99-60a8f14ad6c7
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
