apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-04-12T21:01:20Z"
  labels:
    app: customers
  name: customers
  namespace: cnj
  resourceVersion: "44919"
  uid: 78dd4af4-5d31-45eb-8f38-ca552dedfecd
spec:
  clusterIP: 10.105.203.125
  clusterIPs:
  - 10.105.203.125
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: customers
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
